module.exports = {
  nopermlang: "<: x_: 873534429346267157> | Du har inte behörighet att använda det här kommandot.",
  nolang: ": white_check_mark: Språket har ändrats framgångsrikt",
  wronglang: "<: x_: 873534429346267157> | Fel språknamn.",
  samelang: "<: x_: 873534429346267157> | Du använder redan det här språket.",
  languagedone: ": white_check_mark: | Ditt språk har ändrats till engelska.",
  providebug: ": rolling_eyes: - Please Please The Bug",
  owner: "<: x_: 873534429346267157> | Tyvärr kan du inte använda det här kommandot eftersom du inte är Botens ägare",
  error_no_perms_or_channel: "Jag hittar inte kanalen, kontrollera mina behörigheter | <: x_: 873534429346267157>",
  error: "Fel",
  nonameapp: "Skriv appnamn för att börja söka",
  notfoundapp: "Kan inte hitta appen",
  calcgivesome: "Vänligen skriv matematikproblem för att lösa",
  calcinvaild: "Vänligen skriv in ett vaild -matteproblem för att lösa",
  calcoperation: "Operation",
  calcresult: "Resultat",
  head: "Heads",
  tail: "Tails",
  Flipped: "Vänd",
  entersometext: "Vänligen skriv in lite text",
  nostatus: "Den här användaren har ingen anpassad status",
  status: "Status",
  customstatus: "Anpassad status",
  spotifytrackinfo: "Spotify Track Info",
  songname: "Song Name",
  album: "Album",
  författare: "Författare",
  trackurl: "Song Url",
  statustype: "Statustyp",
  statusapp: "App",
  detaljer: "Detaljer",
  workingon: "Working ON",
  ttstext: "Vänligen ange TTS -text!",
  ttsletters: "Vänligen ange tecken mellan 0 - 1024",
  ttschannel: "Vänligen ange röstrum först!",
  usernamegames: "Vänligen ange spelets användarnamn",
  plattformsspel: "Vänligen skriv spelplattform",
  gamesstatserror: "Jag kan inte hitta statistik för detta användarnamn",
  apex: "Apex Legends",
  userplay: "Snälla, nämn en användare att spela med!",
  vailduser: "Vänligen ange en Vaild -användare!",
  botuser: "Du kan inte leka med robotar!",
  userame: "Du kan inte leka med dig själv",
  wait: "Vänta tills det aktuella spelet slutar",
  acceptera: "Accepterar du att spela (typ: ja)",
  doesnt: "Ser ut att användaren inte vill spela",
  column: "Vilken kolumn du väljer?",
  win: "Win",
  inaktivitet: "Spelet slutade på grund av inaktivitet",
  draw: "Draw!",
  ready: "Ready Up, Spelet börjar när som helst",
  ingen: "Ingen vann!",
  horserace: "Vänligen välj vilken häst som helst att spela på!",
  nobets: "Tyvärr, jag kan inte tävla utan insatser!",
  horsewin: "Bra jobbat! Din häst vann!",
  älskar: "Älskar",
  howmuch: "Så mycket",
  vägbeskrivning: "Hur många vägbeskrivningar vill du behöva memorera?",
  selectmemory: "Du kan bara välja mellan 1 - 20!",
  writeesee: "Skriv vad du såg, bara orden!",
  timeup: "Time Uup! Det var",
  wrongmemory: "Du skrev det fel, det var",
  rps: "Spela ett spel med RPS mot boten! \ nVälj reaktioner att spela!",
  vann: "Vann",
  tie: "Slips",
  lost: "Lost",
  side: "Vilken sida väljer du?",
  duration: ": rolling_eyes: - Ange en Vaild -längd",
  vinnare: ": rolling_eyes: - Välj antal vinnare",
  prize: ": rolling_eyes: Vänligen skriv ett Vaild -pris",
  messageid: ": rolling_eyes: - du måste ange ett giltigt meddelande -ID",
  giveawayend: "Giveaway kommer att sluta på mindre än",
  sekunder: "S",
  giveawayended: ": rolling_eyes: Giveaway är redan avslutad!",
  avatar: "Avatar",
  base: "Vilken användare skulle du vilja vara basen?",
  overbase: "Vilken användare skulle du vilja lägga över basen?",
  pleasewait: "Snälla vänta ...",
  price: "Pris",
  utvecklare: "Utvecklare",
  poäng: "Betyg",
  channelinfo: "Kanalinformation",
  whatareyousearching: ": rolling_eyes: Vad söker du",
  noresult: "Inga resultat",
  emoji: "Emojis",
  animatedemoji: "Animerade emojis",
  invitetracker: "Bjud in spårare för",
  infoinvite: "Bjuder in information till",
  noinvited: "Inga inbjudna personer",
  invitecodes: "Inbjudningskoder",
  botslevel: "Bot's Doesn't Have XP",
  disabledlevel: "Meddelanden om nivåhöjning är för närvarande inaktiverade!",
  enable: "Att aktivera",
  currentlevel: "Current Level",
  totalxp: "Totalt XP",
  neededxp: "Behövs XP för att nå nästa nivå",
  ip: "IP",
  port: "Port",
  version: "Behövs uppdatering",
  spelare: "Spelare räknas",
  maxplayes: "Max Players",
  userlevelthanks: "Användarnivå",
  totalthanks: "Totalt användar tack",
  behörigheter: "Behörigheter",
  pollspeach: "omröstningstal",
  omröstning: "Poll For",
  level: "Level",
  xprank: "XP Rank",
  enterrole: ": rolling_eyes: Vänligen ange en roll i Vaild",
  vaildrole: ": rolling_eyes: Ange en roll i Vaild",
  kickhelp: "Kick Hjälp",
  name: "Servernamn",
  creation_date: "Datum för skapande",
  members: "Members Count",
  id:"ID",
  owner: "Serverägare",
  kanaler: "Kanaler räknas",
  boost_count: "Boost Count",
  shardid: "Shard ID",
  genvägar: "Genvägar",
  använder: "Användningar",
  exempel: "Exempel",
  userisnotintheguild: "Användaren finns inte i guilden",
  kickyourself: "Du kan inte sparka dig själv",
  kickbots: "I Can't Kick This Bot!",
  kickuser: "I Cant Kick This User",
  hasbeenkicked: "Var sparkad för",
  sparkade: "Kicked",
  låst: "Låst",
  unlocked: "Unlocked",
  minnachannl: "Snälla män
  specifymsg: "Skriv ett Vaild -meddelande att skicka",
  sentmessage: "Klart skickat",
  mutehelp: "Stäng av hjälp!",
  idonthaveperms: "Jag har inte tillstånd att stänga av medlemmar [MANAGE_GUILD]",
  youdonthaveperms: "Jag har inte tillstånd att stänga av användare! [MANAGE_GUILD]",
  vaildusermute: "Vänligen ange en Vaild att stänga av!",
  muteyourself: "You Can't Mute YourSelf",
  mutebots: "I Can't Mute This Bot",
  havemuted: "Hej, du fick tyst in",
  orsak till",
  utan framgång: "avstängd",
  framgångsrikt: "framgångsrikt",
  nukingchannel: "Nuking Channel",
  chat: "Chatta",
  hasbeennuked: "Channel Has Been Nuked",
  whatrole: "Vilken ** roll ** skulle du vilja ge? (använd id eller omnämn)",
  whatemoji: "Vilken ** emoji ** vill du att användare ska reagera med? (anpassade emojis fungerar inte)",
  whattext: "Vad skulle du vilja att texten i ** meddelandet ** ska vara (använd --skip för att få standardtext)",
  whatchannel: "Var vill du skicka det här meddelandet? (använd kanalnamn -id eller omnämn)",
  bekräfta: "bekräfta",
  reagera: "Reagera för att ta emot rollen",
  cancelcommand: "Avbrutet kommando",
  logschannelset: "Loggkanalen har ställts in framgångsrikt",
  enterchannelnameorid: "Vänligen ange ett kanalnamn eller ID för att ställa in !!",
  alreadyset: "Denna kanal är redan inställd som loggkanal",
  modlogset: "Aktiverade logg",
  muteroleset: "Muterole Set in This Server Is",
  rolenameorid: "Vänligen ange ett rollnamn eller ID för att ställa in!",
  alreadymuterole: "Denna roll är redan inställd som Muterole!",
  nicknamepermsbot: "Jag måste ha [CHANGE_NICKNAME] tillstånd",
  user: ": rolling_eyes: - Ange en användare!",
  enternickname: "Vänligen ange ett smeknamn",
  modifiednickname: "Ändrat smeknamn på",
  to: "To",
  prefixinthisserver: "Prefix i denna server är:",
  enterprefix: "Vänligen ange ett prefix att ställa in!",
  alreadyprefix: "Detta är redan serverprefixet!",
  setprefix: "Ange Serverprefix framgångsrikt till",
  alreadyxp: "XP -meddelanden är redan aktiverade på servern!",
  enabledxp: "XP -meddelanden har aktiverats framgångsrikt !!",
  unbaned: "har blivit avstängd!",
  nomuterole: "Det finns ingen tyst roll att ta bort!",
  unmutedmsgauthor: "Hej, du har stängts av",
  unmute: "kunde inte stängas av.",
  warnyourself: "Kan inte varna dig själv!",
  warningreason: "Har blivit varnad för",
  varnade: "Har blivit varnad!",
  dagar: "dagar",
  timmar: "Timmar",
  minuter: "minuter",
  sekunder: "Sekunder",
  badge_information: "Märkesinformation",
  user_doesnt_have_any_badges: "Användaren har inga märken",
  user_name: "Användarnamn:",
  tag: "Tag:",
  id:"ID",
  current_status: "Nuvarande status:",
  aktivitet: "Aktivitet:",
  avatar_link: "Avatarlänk:",
  click_here: "Klicka här",
  creation_dateuser: "Gick med i Discord",
  joined_date: "Ansluten server",
  user_roles: "Användarroller:",
  you_have_thanked: "Du har tackat",
  user_level: "Användarnivå",
  delete_message: "** Raderat meddelande: **",
  join_voice: "Gå med i en röstkanal!",
play_betrayal: "Play Betrayal (CLick)",
congrats: "Grattis",
chess: "Spela schack (CLick)",
whowannafight: "Vem ska du slåss?",
clicktofight: "Klicka för att slåss med",
hit_fight: "HIT",
heal_fight: "HEAL",
cancel_fight: "AVBRYT",
cancel: "Avbryt",
play_fishing: "Play Fishing (CLick)",
winneris: "Vinnaren är",
tmemorize: "Du har 10 sekunder att memorera -",
youwon: "Du vann!",
play_poker: "Play Poker (CLick)",
orm: "Ormspel",
gameover: "Game Over",
help_menu: "Hjälpmeny",
help_desc: "Tryck på valfri knapp för att få hjälpkategorin för den",
help_admin: "Admin -kommandon",
help_games: "Spelkommandon",
help_images: "Bilderkommandon",
help_fun: "Roliga kommandon",
help_giveaways: "Giveaways -kommandon",
help_info: "Info -kommandon",
help_welcome: "Welcome Commads",
help_protection: "Skyddskommandon",
help_premium: "Premiumkommandon",
help_youtube: "Youtube -kommandon",
help_leveling: "Utjämningskommandon",
help_voice: "Röstkommandon",
premium_false: "Premium är inte aktiverat på denna server",
remove_value: "Ta bort",
all_value: "Alla",
bots_value: "Bots",
human_value: "Människor",
text_value: "Text",
voice_value: "Voice",
invite_value: "Bjud in",
both_value: "Båda",
day_value: "Day",
week_value: "Vecka",
month_value: "Month",
top_leaderboards: "📋 Guild Score Leaderboards",
top_text_score: ": speech_balloon: TEXT SCORE",
top_voice_score: ": microphone2: VOICE SCORE",
req_by: "Begärt av",
command: "Kommando",
catagory: "Kategori",
command_description: "Beskrivning",
no_desc: "Ingen beskrivning tillhandahålls",
no_usage: "Ingen användning",
aliases_none: "Ingen",
alias: "Alias:",
command_permission: "Tillstånd",
command_usage: "Användning",
no_perm_required: "Inget tillstånd krävs",
enter_emoji: ": rolling_eyes: - Ange en Vaild Emoji",
invaild_emoji: ": rolling_eyes: - Invaild Emoji!",
links: "Länkar",
Confirmation: "Bekräftelse",
cancel_info: "Är du säker på att du vill avbryta Premium -prenumeration för",
success: ": white_check_mark: Success",
cancelled_premium: "Avbruten premie för denna server",
process_canceled: "Process avbruten",
premium_remain: "Premium kvarstår för denna server!",
capture_what_website: ": rolling_eyes: Ange en webbplats för att fånga",
capture_nsfw: ": rolling_eyes: - Du får inte fånga nsfw -webbplatser",
bad_req: "404: Dålig begäran",
channel_not_found: ": rolling_eyes: - Kanal hittades inte",
channel_nsfw: "NSFW",
channel_id: "Id",
channel_type: "Typ",
channel_description: "Beskrivning",
channel_created_timestamp: "Kanal skapad på",
no_result: ": rolling_eyes: - Inga resultat!",
jump_to_message: "Hoppa till meddelande",
power_description: ": sparkles: Power Bot är bot som har mer än 170+ kommandon! Njut av <: heart: 869112808707604521>",
power_invite: "Power Invite",
power_invite_to_server: "Bjud in till din server",
invitites_not_invited: ": rolling_eyes: - Den här användaren har inte inbjudningar!",
lb_nobody: ": rolling_eyes: - Det finns ingen kropp i topplistan, försök igen!",
memberslb: "Members leaderboard",
minecraft_vaild_ip: ": rolling_eyes: - Ange en vaild minecraft server ip",
not_found: "Hittades inte",
ip_invaild: ": rolling_eyes: - Denna ip är invaild!",
thanks_none: ": rolling_eyes: - Den här användaren har inget tack!",
no_permissions: "Inga behörigheter",
all_permissions: "Alla behörigheter",
ping: "Ping ...",
bot_usage: "Botanvändning",
time_taken: "Time taken",
discord_api: "Discord api",
ping_ram: "Ram",
bot_uptime: "Uptime",
ping_average: "Genomsnitt",
ping_write: "Skriv",
ping_read: "Läs",
poll_message_id: ": rolling_eyes: - Ange id för omröstningsmeddelande!",
poll_error_none: ": rolling_eyes: - Det här är inte en vaild -undersökning!",
poll_ended: ": rolling_eyes: - Denna omröstning slutade redan!",
poll_stats: "Enkätstatistik",
poll_2options: "Stöder nu endast omröstning med 2 alternativ",
poll_desc: "Ange omröstningsalternativ, exempel: {Power Bot} [Power Bot] [Power Bot Canary] [Zmk] | Du kan lägga till upp till 20 alternativ",
qrcode_error_fetch: ": rolling_eyes: - Jag kan inte hämta denna qrcode!",
bug_reported: ": white_check_mark: Bug rapporterad",
thanks_help: "Tack för hjälp med att förbättra botten: gnistrar:",
role_id: "Roll -id",
role_name: "Rollnamn",
role_hex: "Roll hex",
role_members: "Rollmedlemmar",
role_position: "Rollposition",
role_mentionable: "Roll nämns?",
enter_role: ": rolling_eyes: - Ange en roll!",
role_list_long: ": rolling_eyes: - Listan över rollmedlemmar är för lång för mig",
users_with_the: "Användare med rollen",
config_premium: "Premium",
config_prefix: "Prefix",
config_language: "Språk",
config_welcome_channel: "Välkomstkanal",
config_welcome_color: "Välkomstfärg",
config_welcome_bg: "Välkomstbakgrund",
rank_enter: ": rolling_eyes: - Ange en bakgrundsadress för att ställa in!",
rank_done: ": white_check_mark: Done, Configured the Rank background",
short_enter: ": rolling_eyes: - Ange en webbadress till short!",
snipe_none: ": rolling_eyes: - Det finns inga raderade meddelanden!",
snipe_deleted: "Borttaget meddelande",
thank_cooldown: ": rolling_eyes: You'e on cooldown",
thank_yourself: ": rolling_eyes: - Du kan inte tacka dig själv!",
level_delete: ": white_check_mark: Klart, borttagna data för",
level_stats: "Nivåstatistik",
level_has: "Har",
level_level: "Level (s)",
level_xp: "XP",
level_needed: "Behövs xp för att nå nästa nivå",
level_none: ": rolling_eyes: - Den här användaren har ingen nivå!",
level_rank_card: "Rankingskort för",
voice_blacklisted: "Svartlistad",
voice_reset_info: "Är du säker på att du vill återställa röst för",
voice_clear_success: "Rensade röstdata för framgångsrikt",
voice_data_remain: "Röstdata kvarstår!",
voice_unblacklist: "Ej svartlistad",
voice_user_none_level: ": rolling_eyes: - Det ser ut som att den här användaren inte har röstnivå!",
voice_time: "Voice Time",
of_voice_time: "av rösttid",
antibot_pro: "Anti-Bot-skydd",
antibot_on: "Ställ antibot -växeln till: PÅ",
antibot_off: "Ställ antibot -växeln till: AV",
no_query: "Ange en vaild -fråga: på, av",
antilink_pro: "Skydd mot länkar",
antilink_on: "Ställ in Antilänkar växla till: PÅ",
antilink_off: "Ställ in Antilänkar växla till: AV",
antispam_pro: "Skydd mot skräppost",
antispam_on: "Ställ in antispam -växeln till: PÅ",
antispam_off: "Ställ in antispam -växeln till: AV",
yt_ch_link: ": rolling_eyes: - Ange en YouTube -kanallänk",
yt_subs: "Prenumeranter",
yt_tags: "Taggar",
yt_unlisted: "Olistad",
yt_family_safe: "FamilySafe",
yt_id: "ID",
yt_replace: "Ersättningar",
yt_post: "Jag lägger upp nya videor för",
yt_channels: "Kanaler",
use: "Användning:",
games_youhave: "You Have",
games_tofind: "för att hitta de dolda orden i meningen nedan",
games_sen: "Mening:",
games_words_found_remaining: "Ord hittade/återstående ord:",
games_wordsfound: "Hittade ord:",
games_words: "Words:",
games_win: "GG, du vann! Du klarade dig",
games_betterluck: "Bättre lycka nästa gång!",
games_wrongguess: "Fel gissning! Du har ** {{återstående_försök}} ** försök kvar",
games_correct: "GG, ** {{word}} ** var korrekt! Du måste hitta ** {{resterande}} ** fler ord",
games_othermessage: "Endast <@{{author}}> kan använda knapparna!",
games_you_have_time: "Du har ** {{time}} ** att skriva nedanstående mening",
games_fast_win: "GG, du har en wpm på ** {{wpm}} ** och du klarade det i ** {{time}} **",
games_fast_lose: "Bättre lycka nästa gång!",
games_fast_cancel: "Du avslutade spelet!",
fight_hit: "Hit",
fight_heal: "Heal",
fight_cancel: "Stoppa",
fight_accept: "Acceptera",
fight_deny: "Förneka",
fight_win: "GG, <@{{winner}}> Vann kampen!",
fight_end: "<@{{opponent}}> svarade inte i tid. Så jag tappade spelet!",
fight_cancel: "<@{{opponent}}> vägrade att slåss med dig!",
fight_fight: "{{player}} du går först!",
fight_op_turn: "Vänta tills dina motståndare flyttar!",
fight_high_health: "Du kan inte läka om din HP är över 80!",
fight_low_health: "Du kan inte avbryta kampen om din HP är under 50!",
guess_number_desc: "Du har ** {{tid}} ** att gissa antalet.",
guess_number_public: "'GG, numret som jag gissade var ** {{number}} **. <@{{winner}}> gjorde det i ** {{time}} **. \ n \ n __ ** Statistik av spelet: ** __ \ n ** Varaktighet **: {{tid}} \ n ** Antal deltagare **: {{totalparticipants}} Deltagare \ n ** Deltagare **: {{deltagare}} " ,
guess_number_private: "GG, numret som jag gissade var ** {{number}} **. Du klarade det i ** {{time}} **",
guess_number_lose: "Bättre lycka nästa gång! Antalet som jag gissade var ** {{number}} **",
guess_number_big_number: "Nej {{author}}! Mitt nummer är större än ** {{number}} **",
guess_number_small_number: "Nej {{author}}! Mitt nummer är mindre än ** {{number}} **.",
guess_number_on_going: "Ett spel körs redan i <#{{channel}}>. Du kan inte starta ett nytt!",
quick_wait: "Knapparna kan visas när som helst nu!",
quick_start: "Första personen som trycker på rätt knapp kommer att vinna. du har ** {{time}} **!",
quick_win: "GG, <@{{winner}}> tryckte på knappen på ** {{time}} sekunder **",
quick_lose: "Ingen tryckte på knappen i tid. Så, jag tappade spelet!",
em_add: "**: rolling_eyes: - Skriv Emoji/(s) för att lägga till! **",
em_successfully: "Tillagd till servern framgångsrikt",
clear_vaild: "**: rolling_eyes: - Ange ett vaild -nummer **",
clear_less: "**: rolling_eyes: - Ange ett tal mindre än 100 **",
clear_more_than_1: "**: rolling_eyes: - Ange ett tal som är mer än 1 **",
clear_success: "framgångsrikt borttagen",
disable_option: "**: rolling_eyes: - Ange ett inaktiveringsalternativ, Alternativ: kanal **",
disable_enter_channel: "**: rolling_eyes: - Ange en kanal **",
disable_done: "<: check: 855651069317480488> ** Klar, inaktiverad **",
enable_option: "**: rolling_eyes: - Ange ett aktiveringsalternativ, Alternativ: kanal **",
enable_enter_channel: "**: rolling_eyes: - Ange en kanal **",
enable_done: "<: check: 855651069317480488> ** Klar, aktiverad **",
log_t: "Log Toggle är nu:",
emoji_not_found: "**: rolling_eyes: - Emoji finns inte på den här servern **",
emoji_parse: "**: rolling_eyes: - Kan inte analysera den inmatade emoji **",
emoji_success: "<: check: 855651069317480488> ** Denna emoji har tagits bort **",
role_cmd: "Rollkommando",
role_specify_member: "**: rolling_eyes: - Ange en medlem **",
role_not_found: "**: rolling_eyes: - Rollen hittades inte **",
role_cant_manage: "**: rolling_eyes: - Jag kan inte hantera den här användaren **",
role_you_cant: "**: rolling_eyes: - Du kan inte hantera den här användaren **",
role_cant_give: "**: rolling_eyes: - Kan inte ge rollen **",
role_remove: "Borttagen",
från: "från",
role_add: "Tillagd",
to: "To",
autorole_reset: "<: check: 855651069317480488> ** Klar, återställ den automatiska rollen **",
autorole_perms: "**: rolling_eyes: - Du kan inte lägga till en roll som har administrationsbehörigheter",
autorole_done: "<: check: 855651069317480488> ** Klar, Autorole inställd som **",
missing_args: "Misssing -argument",
embedcolor_already: "**: rolling_eyes: - Denna inbäddningsfärg är redan inställd! **",
embedcolor_success: "<: check: 855651069317480488> ** Ställ in embedcolor **",
lang_select: "Välj servern språk",
lang_select_below: "Välj serverns språk nedan",
line_no_data: "**: rolling_eyes: - Ingen data hittades **",
line_done: "<: check: 855651069317480488> ** Klar, ställ in radkonfigurationen **",
enter_channel: "**: rolling_eyes: - ange kanal! **",
images_successfully_set: "<: check: 855651069317480488> ** Inställd **",
images_as_only: "** som enbart bildkanal! ** | Återställ typ: imageschannel reset <channel>",
slowmode_specify_time: "**: rolling_eyes: - Ange en tid*",
slowmode_done: "<: check: 855651069317480488> ** Slowmode är nu",

// Permissions
  manage_emojis: "<: x_: 873534429346267157> | Tyvärr, du har inte [MANAGE_EMOJIS] tillstånd",
  manage_webhooks: "<: x_: 873534429346267157> | Tyvärr har du inte [MANAGE_WEBHOOKS] tillstånd",
  manage_messages: "<: x_: 873534429346267157> | Tyvärr, du har inte [MANAGE_MESSAGES] tillstånd",
  manage_roles: "<: x_: 873534429346267157> | Tyvärr har du inte [MANAGE_ROLES] tillstånd",
  manage_guild: "<: x_: 873534429346267157> | Tyvärr har du inte [MANAGE_GUILD] tillstånd",
  manage_channels: "<: x_: 873534429346267157> | Tyvärr har du inte [MANAGE_CHANNELS] tillstånd",
  admin: "<: x_: 873534429346267157> | Tyvärr har du inte [ADMINISTRATOR] tillstånd",
  attach_files: "<: x_: 873534429346267157> | Tyvärr har du inte [ATTACH_FILES] tillstånd",
  ban_members: "<: x_: 873534429346267157> | Tyvärr har du inte [BAN_MEMBERS] tillstånd",
  change_nickname: "<: x_: 873534429346267157> | Tyvärr har du inte [CHANGE_NICKNAME] tillstånd",
bot_manage_guild: "<: x_: 873534429346267157> | Jag har inte [MANAGE_GUILD] tillstånd!",
bot_manage_emojis: "<: x_: 873534429346267157> | Jag har inte [MANAGE_EMOJIS] tillstånd!",

  }